<?php

namespace TearoomOne;

use Kirby\Cms\App as Kirby;

class Robots
{
    protected $kirby;
    protected $config;

    // Known bad bots that should be blocked
    const BAD_BOTS = [
        'AhrefsBot',
        'SemrushBot',
        'MJ12bot',
        'DotBot',
        'BLEXBot',
        'PetalBot',
        'DataForSeoBot',
        'Pinterestbot/1.0',
        'MegaIndex.ru',
        'SeekportBot',
        'serpstatbot',
        'AspiegelBot',
    ];

    public function __construct(Kirby $kirby)
    {
        $this->kirby = $kirby;
        $this->config = $kirby->option('tearoom1.meta-kit.robots', []);
    }

    /**
     * Generate complete robots.txt content
     */
    public function generate(): string
    {
        $site = $this->kirby->site();

        // Get robots settings from panel
        $robotsData = MetaHelper::getSeoData($site->metaKitRobots());

        // If no robots data exists yet, return basic
        if (!$robotsData) {
            return $this->generateBasic();
        }

        // Check if custom robots is enabled
        $enabled = $this->getOption($robotsData, 'enabled', true);

        if (!$enabled) {
            return $this->generateBasic();
        }

        $lines = [];

        // Add header comment
        $lines[] = "# Robots.txt for " . $site->url();
        $lines[] = "# Generated by Meta Kit for Kirby";
        $lines[] = "";

        // Add custom rules from panel or config
        $customRules = $this->getCustomRules($robotsData);
        if (!empty($customRules)) {
            foreach ($customRules as $rule) {
                $lines = array_merge($lines, $this->formatRule($rule));
                $lines[] = "";
            }
        }

        // Block bad bots if enabled
        $blockBadBots = $this->getOption($robotsData, 'blockBadBots', false);
        if ($blockBadBots || ($this->config['blockBadBots'] ?? false)) {
            $lines = array_merge($lines, $this->generateBadBotRules());
            $lines[] = "";
        }

        // Add default rules if enabled
        $defaultRules = $this->getOption($robotsData, 'defaultRules', true);
        if ($defaultRules) {
            $lines[] = "User-agent: *";
            $lines[] = "Allow: /";
            $lines[] = "";
            // disallow panel
            $lines[] = "Disallow: /panel/";
            $lines[] = "";
        }

        // Add custom directives
        $customDirectives = $this->getOption($robotsData, 'customDirectives', '');
        if (!empty($customDirectives)) {
            $lines[] = trim($customDirectives);
            $lines[] = "";
        }

        // Add config-based custom directives
        if (!empty($this->config['customDirectives'])) {
            $lines[] = trim($this->config['customDirectives']);
            $lines[] = "";
        }

        // Add sitemap reference
        $includeSitemap = $this->getOption($robotsData, 'includeSitemap', true);
        if ($includeSitemap) {
            $sitemapUrl = $this->kirby->url() . '/sitemap.xml';
            $lines[] = "Sitemap: " . $sitemapUrl;
        }

        return implode("\n", $lines);
    }

    /**
     * Generate basic robots.txt
     */
    protected function generateBasic(): string
    {
        $lines = [];
        $lines[] = "User-agent: *";
        $lines[] = "Allow: /";

        // disallow panel
        $lines[] = "Disallow: /panel/";

        // Always include sitemap in basic mode
        $sitemapUrl = $this->kirby->url() . '/sitemap.xml';
        $lines[] = "";
        $lines[] = "Sitemap: " . $sitemapUrl;

        return implode("\n", $lines);
    }

    /**
     * Get custom rules from panel data or config
     */
    protected function getCustomRules($robotsData): array
    {
        $rules = [];

        // Get rules from panel
        if ($robotsData) {
            $panelRules = $robotsData->customRules()->toStructure();
            foreach ($panelRules as $rule) {
                $userAgent = $rule->userAgent()->value();

                // Handle custom user agent
                if ($userAgent === 'custom' && $rule->customUserAgent()->isNotEmpty()) {
                    $userAgent = $rule->customUserAgent()->value();
                }

                $ruleData = [
                    'userAgent' => $userAgent,
                    'allow' => $rule->allowPaths()->isNotEmpty() ? $rule->allowPaths()->split(',') : [],
                    'disallow' => $rule->disallowPaths()->isNotEmpty() ? $rule->disallowPaths()->split(',') : [],
                    'crawlDelay' => $rule->crawlDelay()->isNotEmpty() ? $rule->crawlDelay()->toInt() : null,
                ];

                $rules[] = $ruleData;
            }
        }

        // Merge with config rules
        if (!empty($this->config['rules'])) {
            $rules = array_merge($rules, $this->config['rules']);
        }

        return $rules;
    }

    /**
     * Format a single rule
     */
    protected function formatRule(array $rule): array
    {
        $lines = [];

        $lines[] = "User-agent: " . $rule['userAgent'];

        // Add allow directives
        if (!empty($rule['allow'])) {
            foreach ($rule['allow'] as $path) {
                $path = trim($path);
                if (!empty($path)) {
                    $lines[] = "Allow: " . $path;
                }
            }
        }

        // Add disallow directives
        if (!empty($rule['disallow'])) {
            foreach ($rule['disallow'] as $path) {
                $path = trim($path);
                if (!empty($path)) {
                    $lines[] = "Disallow: " . $path;
                }
            }
        }

        // Add crawl delay if specified
        if (!empty($rule['crawlDelay']) && $rule['crawlDelay'] > 0) {
            $lines[] = "Crawl-delay: " . $rule['crawlDelay'];
        }

        return $lines;
    }

    /**
     * Generate rules to block bad bots
     */
    protected function generateBadBotRules(): array
    {
        $lines = [];
        $lines[] = "# Block known scrapers and spam bots";

        foreach (self::BAD_BOTS as $bot) {
            $lines[] = "User-agent: " . $bot;
            $lines[] = "Disallow: /";
            $lines[] = "";
        }

        return $lines;
    }

    /**
     * Get option with fallback priority: panel -> config -> default
     */
    protected function getOption($robotsData, string $key, $default = null)
    {
        // Try panel data first
        if ($robotsData && $robotsData->has($key)) {
            $value = $robotsData->$key();
            if ($value && !$value->isEmpty()) {
                // Handle toggle/boolean fields
                if (method_exists($value, 'toBool')) {
                    return $value->toBool();
                }
                return $value->value();
            }
        }

        // Try config
        if (isset($this->config[$key])) {
            return $this->config[$key];
        }

        // Return default
        return $default;
    }
}
